apiVersion: v1
kind: Service
metadata:
  name: city-api-app
  labels:
    app: city-api-app
    environment: {{ .Values.app.env_name }}
spec:
  type: NodePort
  selector:
    app: city-api-app
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ required "app.nodePort is required" .Values.app.nodePort }}