apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-api-app
  template:
    metadata:
      labels:
        app: city-api-app
    spec:
      containers:
        - name: city-api
          image: {{ printf "%s:%s" .Values.app.image .Values.app.tag }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: CITY_API_ADDR
              value: {{ .Values.app.addr }}
            - name: CITY_API_PORT
              value: {{ .Values.app.port | quote }}
            - name: CITY_API_DB_URL
              value: {{ .Values.db.host }}
            - name: CITY_API_DB_USER
              value: {{ .Values.db.user }}
            - name: CITY_API_DB_PWD
              value: {{ .Values.db.password }}
