apiVersion: v1
kind: Ingress
metadata:
  name: city-api-{{ .Values.app.env_name }}
  labels:
    app: city-api
    environment: {{ .Values.app.env_name }}
spec:
  rules:
    - host: {{ printf "city-api-%s.localhost" .Values.app.env_name}}
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: city-api-{{ .Values.app.env_name}}-app
              port:
                number: {{ .Values.app.port }}