apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-api-{{ .Values.app.env_name }}-db
  labels:
    app: city-api-db
    environment: {{ .Values.app.env_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-api-db
      environment: {{ .Values.app.env_name }}
  template:
    metadata:
      labels:
        app: city-api-db
        environment: {{ .Values.app.env_name }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-script
          configMap:
            name: city-api-init
        - name: db-storage
          persistentVolumeClaim:
            claimName: city-api-pvc
