version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: city_api
      POSTGRES_USER: city_api
      POSTGRES_PASSWORD: city_api
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - city_api_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      CITY_API_ADDR: "0.0.0.0"
      CITY_API_PORT: "2022"
      CITY_API_DB_URL: "db:5432/city_api"
      CITY_API_DB_USER: "city_api"
      CITY_API_DB_PWD: "city_api"
    ports:
      - "2022:2022"
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  city_api_data:
  prometheus_data:
  grafana_data:


