version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: cityapi
    environment:
      POSTGRES_USER: cityapi
      POSTGRES_PASSWORD: cityapi
      POSTGRES_DB: cityapi
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
