apiVersion: v1
kind: Service
metadata:
  name: city-api-db
spec:
  selector:
    app: city-api-db
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
