apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cityapi
  namespace: cityapi
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      # When using a Pull Request generator, the ApplicationSet controller polls every `requeueAfterSeconds` interval (defaulting to every 30 minutes) to detect changes.
      requeueAfterSeconds: 300
      github:
        owner: aurianecodebien
        repo: CityApi
  template:
    metadata:
      name: 'myapp-{{.branch}}-{{.number}}'
    spec:
      source:
        repoURL: 'https://github.com/aurianecodebien/CityApi.git'
        targetRevision: '{{.head_sha}}'
        path: kubernetes/
        helm:
          parameters:
            - name: "image.tag"
              value: "pr-{{.author}}-{{.head_sha}}"
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: cityapi
