apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: city-api-prod-db
  labels:
    app: city-api-app
    environment: prod
spec:
  databaseReclaimPolicy: retain
  name: city_api-prod-pg
  cluster:
    name: city-api-pg
  owner: city_api