apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cityapi
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.27/releases/cnpg-1.27.0.yaml
  - argo-cd.yaml
  - cluster-secret.yaml
  - cluster.yaml
  - database-prod.yaml
patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: cityapi
    target:
      kind: ClusterRoleBinding
