name: Deploy PR Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr,prefix=pr-

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # TODO: Ajouter le déploiement Kubernetes ici
      # Décommenter quand Kubernetes est configuré avec les credentials
      
      # - name: Deploy to Kubernetes
      #   env:
      #     PR_NUMBER: ${{ github.event.pull_request.number }}
      #   run: |
      #     # Installer kubectl et helm si nécessaire
      #     # Configurer kubeconfig avec ${{ secrets.KUBE_CONFIG }}
      #     
      #     helm upgrade --install cityapi-pr-${PR_NUMBER} ./kubernetes/helm \
      #       -f ./kubernetes/helm/values-pr.yaml \
      #       --set prNumber=${PR_NUMBER} \
      #       --set app.tag=pr-${PR_NUMBER} \
      #       --namespace cityapi-pr-${PR_NUMBER} \
      #       --create-namespace \
      #       --wait

      - name: Comment PR with deployment info
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Environment PR #${prNumber} déployé !**
              
              📦 Image: \`ghcr.io/${{ github.repository }}:pr-${prNumber}\`
              🗄️ Database: \`pr_${prNumber}\` (copie de prod)
              
              ⚠️ _Déploiement K8s à configurer - voir kubernetes/DATABASE.md_`
            })
